buildscript {
    repositories {
        maven { url = 'https://maven.minecraftforge.net' }
        mavenCentral()
    }
    dependencies {
        classpath 'net.minecraftforge.gradle:ForgeGradle:5.1.+'
    }
}

apply plugin: 'net.minecraftforge.gradle'

archivesBaseName = 'legacyforge'
version = '1.0.0'

dependencies {
    minecraft 'net.minecraftforge:forge:1.12.2-14.23.5.2859'
}
